//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeIT.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class durum
    {
        public int id { get; set; }
        public string durum1 { get; set; }
    }
}
