//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeIT.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjeIT_DbEntities : DbContext
    {
        public ProjeIT_DbEntities()
            : base("name=ProjeIT_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aciliyetDurum> aciliyetDurum { get; set; }
        public virtual DbSet<Calisan> Calisan { get; set; }
        public virtual DbSet<durum> durum { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }
    }
}
