//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeIT.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
        public Nullable<int> aciliyet_durumu { get; set; }
        public Nullable<System.DateTime> bitirilme_sure { get; set; }
        public byte[] dokuman { get; set; }
        public Nullable<int> calisan { get; set; }
        public string durum { get; set; }
        public Nullable<int> yonetici { get; set; }
    
        public virtual aciliyetDurum aciliyetDurum { get; set; }
        public virtual Calisan Calisan1 { get; set; }
        public virtual Yonetici Yonetici1 { get; set; }
    }
}
